### ISSUE TITLE
trouble installing aurora

### ISSUE THREAD

**Issue by jmcclena** [fsciortino/Aurora#10] opened 2020-11-24 05:39 UTC
I get the following error trying to import aurora from python:

```mcclenaghan@F-C02Z321ML ~ % python                      
Python 3.7.9 (default, Sep  6 2020, 13:20:25) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import aurora
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aurorafusion-1.0.11-py3.7-macosx-10.15-x86_64.egg/aurora/__init__.py", line 5, in <module>
    __version__ = pkgutil.get_data("aurora", "version").decode()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py", line 637, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aurorafusion-1.0.11-py3.7-macosx-10.15-x86_64.egg/aurora/version'
>>> 
```

My attempt to install aurora is:

```mcclenaghan@F-C02Z321ML Aurora % sudo python setup.py build --fcompiler=gfortran
Password:
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "aurora._aurora" sources
f2py options: []
  adding 'build/src.macosx-10.15-x86_64-3.7/build/src.macosx-10.15-x86_64-3.7/aurora/fortranobject.c' to sources.
  adding 'build/src.macosx-10.15-x86_64-3.7/build/src.macosx-10.15-x86_64-3.7/aurora' to include_dirs.
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /usr/local/bin/gfortran
customize Gnu95FCompiler using build_ext


mcclenaghan@F-C02Z321ML Aurora % sudo python setup.py install                   
running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "aurora._aurora" sources
f2py options: []
  adding 'build/src.macosx-10.15-x86_64-3.7/build/src.macosx-10.15-x86_64-3.7/aurora/fortranobject.c' to sources.
  adding 'build/src.macosx-10.15-x86_64-3.7/build/src.macosx-10.15-x86_64-3.7/aurora' to include_dirs.
build_src: building npy-pkg config files
writing aurorafusion.egg-info/PKG-INFO
writing dependency_links to aurorafusion.egg-info/dependency_links.txt
writing requirements to aurorafusion.egg-info/requires.txt
writing top-level names to aurorafusion.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'aurorafusion.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.15-x86_64/egg
running install_lib
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'pg']'
customize Gnu95FCompiler
Found executable /usr/local/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
creating build/bdist.macosx-10.15-x86_64/egg
creating build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/animate.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/coords.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/source_utils.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/particle_conserv.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/nbi_neutrals.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/adas_files.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/__init__.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/core.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/plot_tools.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/_aurora.cpython-37m-darwin.so -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/default_nml.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/synth_diags.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/radiation.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/interp.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/janev_smith_rates.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/atomic.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
copying build/lib.macosx-10.15-x86_64-3.7/aurora/grids_utils.py -> build/bdist.macosx-10.15-x86_64/egg/aurora
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/animate.py to animate.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/coords.py to coords.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/source_utils.py to source_utils.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/particle_conserv.py to particle_conserv.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/nbi_neutrals.py to nbi_neutrals.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/adas_files.py to adas_files.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/core.py to core.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/plot_tools.py to plot_tools.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/default_nml.py to default_nml.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/synth_diags.py to synth_diags.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/radiation.py to radiation.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/interp.py to interp.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/janev_smith_rates.py to janev_smith_rates.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/atomic.py to atomic.cpython-37.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/grids_utils.py to grids_utils.cpython-37.pyc
creating stub loader for aurora/_aurora.cpython-37m-darwin.so
byte-compiling build/bdist.macosx-10.15-x86_64/egg/aurora/_aurora.py to _aurora.cpython-37.pyc
creating build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying aurorafusion.egg-info/PKG-INFO -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying aurorafusion.egg-info/SOURCES.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying aurorafusion.egg-info/dependency_links.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying aurorafusion.egg-info/requires.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying aurorafusion.egg-info/top_level.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.15-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
aurora.__pycache__._aurora.cpython-37: module references __file__
aurora.__pycache__.adas_files.cpython-37: module references __file__
aurora.__pycache__.core.cpython-37: module references __file__
creating 'dist/aurorafusion-1.0.11-py3.7-macosx-10.15-x86_64.egg' and adding 'build/bdist.macosx-10.15-x86_64/egg' to it
removing 'build/bdist.macosx-10.15-x86_64/egg' (and everything under it)
Processing aurorafusion-1.0.11-py3.7-macosx-10.15-x86_64.egg
removing '/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aurorafusion-1.0.11-py3.7-macosx-10.15-x86_64.egg' (and everything under it)
creating /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aurorafusion-1.0.11-py3.7-macosx-10.15-x86_64.egg
Extracting aurorafusion-1.0.11-py3.7-macosx-10.15-x86_64.egg to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
aurorafusion 1.0.11 is already the active version in easy-install.pth

Installed /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aurorafusion-1.0.11-py3.7-macosx-10.15-x86_64.egg
Processing dependencies for aurorafusion==1.0.11
Searching for omfit-gapy==2020.11.2.20.1
Best match: omfit-gapy 2020.11.2.20.1
Processing omfit_gapy-2020.11.2.20.1-py3.7.egg
omfit-gapy 2020.11.2.20.1 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/omfit_gapy-2020.11.2.20.1-py3.7.egg
Searching for omfit-eqdsk==2020.11.2.20.1
Best match: omfit-eqdsk 2020.11.2.20.1
Processing omfit_eqdsk-2020.11.2.20.1-py3.7.egg
omfit-eqdsk 2020.11.2.20.1 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/omfit_eqdsk-2020.11.2.20.1-py3.7.egg
Searching for xarray==0.16.1
Best match: xarray 0.16.1
Adding xarray 0.16.1 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for matplotlib==3.3.0
Best match: matplotlib 3.3.0
Adding matplotlib 3.3.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for scipy==1.5.4
Best match: scipy 1.5.4
Adding scipy 1.5.4 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for numpy==1.19.4
Best match: numpy 1.19.4
Adding numpy 1.19.4 to easy-install.pth file
Installing f2py script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin
Installing f2py3 script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin
Installing f2py3.7 script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for omfit-commonclasses==2020.11.2.20.1
Best match: omfit-commonclasses 2020.11.2.20.1
Processing omfit_commonclasses-2020.11.2.20.1-py3.7.egg
omfit-commonclasses 2020.11.2.20.1 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/omfit_commonclasses-2020.11.2.20.1-py3.7.egg
Searching for omfit-path==2020.11.2.20.1
Best match: omfit-path 2020.11.2.20.1
Processing omfit_path-2020.11.2.20.1-py3.7.egg
omfit-path 2020.11.2.20.1 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/omfit_path-2020.11.2.20.1-py3.7.egg
Searching for omfit-ascii==2020.11.2.20.1
Best match: omfit-ascii 2020.11.2.20.1
Processing omfit_ascii-2020.11.2.20.1-py3.7.egg
omfit-ascii 2020.11.2.20.1 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/omfit_ascii-2020.11.2.20.1-py3.7.egg
Searching for uncertainties==3.1.5
Best match: uncertainties 3.1.5
Adding uncertainties 3.1.5 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for omas==0.67.0
Best match: omas 0.67.0
Adding omas 0.67.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for omfit-error==2020.11.2.20.1
Best match: omfit-error 2020.11.2.20.1
Processing omfit_error-2020.11.2.20.1-py3.7.egg
omfit-error 2020.11.2.20.1 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/omfit_error-2020.11.2.20.1-py3.7.egg
Searching for omfit-data==2020.11.2.20.1
Best match: omfit-data 2020.11.2.20.1
Processing omfit_data-2020.11.2.20.1-py3.7.egg
omfit-data 2020.11.2.20.1 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/omfit_data-2020.11.2.20.1-py3.7.egg
Searching for omfit-mds==2020.11.2.20.1
Best match: omfit-mds 2020.11.2.20.1
Processing omfit_mds-2020.11.2.20.1-py3.7.egg
omfit-mds 2020.11.2.20.1 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/omfit_mds-2020.11.2.20.1-py3.7.egg
Searching for omfit-namelist==2020.11.2.20.1
Best match: omfit-namelist 2020.11.2.20.1
Processing omfit_namelist-2020.11.2.20.1-py3.7.egg
omfit-namelist 2020.11.2.20.1 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/omfit_namelist-2020.11.2.20.1-py3.7.egg
Searching for omfit-nc==2020.11.2.20.1
Best match: omfit-nc 2020.11.2.20.1
Processing omfit_nc-2020.11.2.20.1-py3.7.egg
omfit-nc 2020.11.2.20.1 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/omfit_nc-2020.11.2.20.1-py3.7.egg
Searching for fortranformat==0.2.5
Best match: fortranformat 0.2.5
Processing fortranformat-0.2.5-py3.7.egg
fortranformat 0.2.5 is already the active version in easy-install.pth

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fortranformat-0.2.5-py3.7.egg
Searching for setuptools==50.3.1
Best match: setuptools 50.3.1
Adding setuptools 50.3.1 to easy-install.pth file
Installing easy_install script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin
Installing easy_install-3.7 script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for pandas==1.1.2
Best match: pandas 1.1.2
Adding pandas 1.1.2 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for python-dateutil==2.8.1
Best match: python-dateutil 2.8.1
Adding python-dateutil 2.8.1 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for pyparsing==2.4.7
Best match: pyparsing 2.4.7
Adding pyparsing 2.4.7 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for Pillow==8.0.1
Best match: Pillow 8.0.1
Adding Pillow 8.0.1 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for kiwisolver==1.2.0
Best match: kiwisolver 1.2.0
Adding kiwisolver 1.2.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for future==0.18.2
Best match: future 0.18.2
Adding future 0.18.2 to easy-install.pth file
Installing futurize script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin
Installing pasteurize script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for tqdm==4.53.0
Best match: tqdm 4.53.0
Adding tqdm 4.53.0 to easy-install.pth file
Installing tqdm script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for pymongo==3.11.0
Best match: pymongo 3.11.0
Adding pymongo 3.11.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for xmltodict==0.12.0
Best match: xmltodict 0.12.0
Adding xmltodict 0.12.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for netCDF4==1.5.4
Best match: netCDF4 1.5.4
Adding netCDF4 1.5.4 to easy-install.pth file
Installing nc3tonc4 script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin
Installing nc4tonc3 script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin
Installing ncinfo script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for Pyro5==5.11
Best match: Pyro5 5.11
Adding Pyro5 5.11 to easy-install.pth file
Installing pyro5-check-config script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin
Installing pyro5-echoserver script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin
Installing pyro5-httpgateway script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin
Installing pyro5-ns script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin
Installing pyro5-nsc script to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for dnspython==2.0.0
Best match: dnspython 2.0.0
Adding dnspython 2.0.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for Pint==0.15
Best match: Pint 0.15
Adding Pint 0.15 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for boto3==1.16.23
Best match: boto3 1.16.23
Adding boto3 1.16.23 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for h5py==3.1.0
Best match: h5py 3.1.0
Adding h5py 3.1.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for pytz==2020.1
Best match: pytz 2020.1
Adding pytz 2020.1 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for six==1.15.0
Best match: six 1.15.0
Adding six 1.15.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for cftime==1.2.1
Best match: cftime 1.2.1
Adding cftime 1.2.1 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for serpent==1.30.2
Best match: serpent 1.30.2
Adding serpent 1.30.2 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for packaging==20.4
Best match: packaging 20.4
Adding packaging 20.4 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for importlib-metadata==1.7.0
Best match: importlib-metadata 1.7.0
Adding importlib-metadata 1.7.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for jmespath==0.10.0
Best match: jmespath 0.10.0
Adding jmespath 0.10.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for s3transfer==0.3.3
Best match: s3transfer 0.3.3
Adding s3transfer 0.3.3 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for botocore==1.19.23
Best match: botocore 1.19.23
Adding botocore 1.19.23 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for cached-property==1.5.1
Best match: cached-property 1.5.1
Adding cached-property 1.5.1 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for zipp==3.1.0
Best match: zipp 3.1.0
Adding zipp 3.1.0 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Searching for urllib3==1.25.10
Best match: urllib3 1.25.10
Adding urllib3 1.25.10 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Finished processing dependencies for aurorafusion==1.0.11
```

**Comment by StanczakDominik** [comment] 2020-11-24 07:40
Oh yeah, that's a semi-duplicate of #8, which I tried dealing with a bit in #9. I haven't yet had the time to continue on that track, but I guess I can try tackling it now.

To summarize what I can parse from the logs:

* similar issue as previously, the `version` file does not get added to the package, this time in an .egg format (which I hadn't tested before);
* MacOS;
* install from cloned github repo, rather than from PyPI (judging from the version number);
* using `sudo python setup.py install` (and to be honest, that's usually a bad idea - instead of messing with your system's set of python libraries, it tends to be better to make a virtual environment or install it into user space; modern versions of pip do `pip install --user` by default).
* requirements seem to have been installed nicely.

That's certainly actionable :smile:

**Comment by StanczakDominik** [comment] 2020-11-24 07:52
Oh yeah, @jmcclena, sorry - as a temporary measure, could you try using `pip install --editable .` or `python setup.py develop` instead? I should have suggested that in the first place, but got carried away thinking about permanent fixes.

**Comment by jmcclena** [comment] 2020-11-24 08:04
@StanczakDominik  `python setup.py develop` seems to have worked. :)

**Comment by StanczakDominik** [comment] 2020-11-24 08:05
Glad to hear that! :+1:

**Closed** 2021-01-26 19:00 UTC
